### Send POST request with json body
POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "user2"
}

### Send POST request with json body
GET http://localhost:8080/user?userName=John doe
Content-Type: application/json
